#!/bin/sh

scr_name="$(basename $0)[$$]"

# Shrink logfile to last 100 lines

LOGFILE="$1"

if [ -f "$LOGFILE" ]; then
	lines=$(wc -l < $LOGFILE)
	if [ $lines -gt 100 ]; then
		tail -n 100 > $LOGILE.tmp
		mv -f $LOGFILE.tmp $LOGFILE
		logger -t $scr_name "log: $LOGFILE has been pruned"
	else
		logger -t $scr_name "log: $LOGFILE does not need to be pruned"
	fi
else
	logger -t $scr_name "log: $LOGFILE not found"
fi

exit 0
