#!/bin/sh

scr_name="$(basename $0)[$$]"

# Shrink logfile to last 100 lines

LOGFILE="$1"

if [ -f "$LOGFILE" ]; then
	lines=$(wc -l < $LOGFILE)
	if [ $lines -gt 100 ]; then
		echo "$(tail -n 100 $LOGFILE)" > $LOGFILE
		logger -s -t $scr_name "log: $LOGFILE $lines total lines $((lines-100)) lines pruned"
#	else
#		logger -s -t $scr_name "log: $LOGFILE $lines total lines"
	fi
else
	logger -s -t $scr_name "log: $LOGFILE not found"
fi

exit 0
